config/routes.rb
Rails.application.routes.draw do
  devise_for :users, skip: :all
  devise_scope :user do
    post '/users' => 'users/registrations#create', as: :user_registration
    patch '/users' => 'users/registrations#update'
    delete '/users' => 'users/registrations#destroy'
    post '/users/sign_in' => 'users/sessions#create', as: :user_session
    delete '/users/sign_out' => 'users/sessions#destroy', as: :destroy_user_session
  end

  namespace :api, { format: 'json' } do
    resources :users, only: [:index, :show]
    get "login_user", to: "users#login_user"
  end

  resources :users, only: [:index, :show] do
    member do
      get "joining"
      get "follow"
      get "unfollow"
    end
  end

  resources :rooms do
    member do
      get "join"
      get "exit"
      post "bookmark", to: "bookmarks#create"
    end

    collection do
      get "search_shop", as: "search_shop"
      get "search"
    end
  end

  resources :notifications, only: :index
  resources :bookmarks, only: [:index, :destroy]
  root "home#index"
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :user
  belongs_to :room

  validates :user_id, presence: true, numericality: { only_integer: true }, uniqueness: { scope: :room_id }
  validates :room_id, presence: true, numericality: { only_integer: true }
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController
  before_action :authenticate_user!, only: [:index, :create, :destroy]

  # GET /bookmarks
  def index
    @bookmarks = current_user.booked_rooms
  end

  # POST /rooms/:id/bookmark
  def create
    @room = Room.find_by(id: params[:id])
    if @room
      current_user.book @room
    else
      flash[:alert] = "Room is not found."
      redirect_back
    end
  end

  # DELETE /bookmarks/:id
  # :id は room_id であることに注意!
  def destroy
    @room = Room.find_by(id: params[:id])
    if @room
      current_user.booked_rooms.delete(@room)
    else
      flash[:alert] = "Room is not found."
      redirect_back
    end
  end

  private

  # xhrリクエストの時、フィルターできなかったので、オーバーライド
  def authenticate_user!
    redirect_to(new_user_session_path, alert: "you need to sign in or sign up before continuing.") unless current_user
  end
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/views/bookmarks/_bookmark_icon.html.erb
<% if room.booked_by?(current_user) %>
  <%= link_to bookmark_path(room), method: :delete, remote: true, class: "card-link book-mark text-bright", id: "bookmark-icon-#{room.id}" do %>
    <svg xmlns="http://www.w3.org/2000/svg" width="25" height="25" fill="currentColor" class="bi bi-bookmark-fill" viewBox="0 0 16 16">
      <path d="M2 2v13.5a.5.5 0 0 0 .74.439L8 13.069l5.26 2.87A.5.5 0 0 0 14 15.5V2a2 2 0 0 0-2-2H4a2 2 0 0 0-2 2z"/>
    </svg>
  <% end %>
<% else %>
  <%= link_to bookmark_room_path(room), method: :post, remote: true, class: "card-link book-mark text-bright", id: "bookmark-icon-#{room.id}" do %>
    <svg xmlns="http://www.w3.org/2000/svg" width="25" height="25" fill="currentColor" class="bi bi-bookmark" viewBox="0 0 16 16">
      <path d="M2 2a2 2 0 0 1 2-2h8a2 2 0 0 1 2 2v13.5a.5.5 0 0 1-.777.416L8 13.101l-5.223 2.815A.5.5 0 0 1 2 15.5V2zm2-1a1 1 0 0 0-1 1v12.566l4.723-2.482a.5.5 0 0 1 .554 0L13 14.566V2a1 1 0 0 0-1-1H4z"/>
    </svg>
  <% end %>
<% end %>

app/views/bookmarks/create.js.erb
$("#bookmark-icon-<%= @room.id %>").html("<%= j(render partial: 'bookmarks/bookmark_icon', locals: { room: @room }) %>");

app/views/bookmarks/destroy.js.erb
$("#bookmark-icon-<%= @room.id %>").html("<%= j(render partial: 'bookmarks/bookmark_icon', locals: { room: @room }) %>");

app/views/bookmarks/index.html.erb
<div class="content">
  <h1>ブックマーク一覧</h1>
  <div class="rooms text-center grid">
    <%= render @bookmarks %>
  </div>
</div>