config/routes.rb
Rails.application.routes.draw do
  devise_for :users, skip: :all
  devise_scope :user do
    post '/users' => 'users/registrations#create', as: :user_registration
    patch '/users' => 'users/registrations#update'
    delete '/users' => 'users/registrations#destroy'
    post '/users/sign_in' => 'users/sessions#create', as: :user_session
    delete '/users/sign_out' => 'users/sessions#destroy', as: :destroy_user_session
  end

  namespace :api, { format: 'json' } do
    resources :users, only: [:index, :show]
    get "login_user", to: "users#login_user"
  end

  resources :users, only: [:index, :show] do
    member do
      get "joining"
      get "follow"
      get "unfollow"
    end
  end

  resources :rooms do
    member do
      get "join"
      get "exit"
      post "bookmark", to: "bookmarks#create"
    end

    collection do
      get "search_shop", as: "search_shop"
      get "search"
    end
  end

  resources :notifications, only: :index
  resources :bookmarks, only: [:index, :destroy]
  root "home#index"
end

app/models/room.rb
class Room < ApplicationRecord
  has_many :memberships, class_name: "Member", foreign_key: "room_id", dependent: :destroy
  has_many :members, through: :memberships, source: :user
  has_many :notifications, dependent: :destroy
  has_many :booked, class_name: "Bookmark", foreign_key: "room_id", dependent: :destroy
  has_many :booked_by, through: :booked, source: :user
  belongs_to :owner, class_name: "User", foreign_key: :user_id

  validates :name, presence: true, length: { maximum: 100 }
  validates :theme, presence: true, length: { maximum: 200 }
  validates :message, length: { maximum: 500 }

  def owner?(user)
    owner == user
  end

  def member?(user)
    members.include?(user)
  end

  def booked_by?(user)
    booked_by.include?(user)
  end
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  protect_from_forgery

  before_action :authenticate_user!, only: [:create, :update, :destroy, :join, :exit]
  before_action :set_room, only: [:show, :update, :destroy, :join, :exit]
  before_action :room_owner?, only: [:update, :destroy]

  # エラーを拾えなかった場合は、500 internal server errorを応答
  rescue_from Exception, with: :render_status_500

  # レコードが見つからなかった場合は、404 not foundを応答
  rescue_from ActiveRecord::RecordNotFound, with: :render_status_404

  # GET /rooms
  def index
    @rooms = Room.all
    render json: {
      result: {
        rooms: @rooms
      }
    }
  end

  # GET /rooms/:id
  def show
    render json: {
      result: {
        room: {
          id: @room.id,
          title: @room.title,
          content: @room.content,
          shop_name: @room.shop_name,
          shop_url: @room.shop_url,
          limit: @room.limit,
          date: @room.date,
          owner_id: @room.owner.id,
          owner_name: @room.owner.name
        }
      }
    }
  end

  # POST /rooms
  def create
    @room = current_user.rooms.build(room_params)
    http_status = @room.save ? :ok : :bad_request
    render json: {
      result: {
        room: @room,
        errors: @room.errors.full_messages
      }
    }, status: http_status
  end

  # PATCH /rooms/:id
  def update
    if @room.update(room_params)
      render json: {
        result: {
          room: @room.reload
        }
      }
    else
      render json: {
        errors: @room.errors.full_messages
      }, status: :bad_request
    end
  end

  # DELETE /rooms/:id
  def destroy
    if @room.destroy
      render json: {}, status: :ok
    else
      render json: {
        errors: '未知のエラー'
      }, status: :bad_request
    end
  end

  # GET /rooms/search_shop
  def search_shop
    term = params[:keyword]
    data = search_shops(term)["results"]["shop"]
    return if data.nil?

    @shops = []
    data.each do |shop|
      @shops << { name: shop["name"], url: shop["urls"]["pc"] }
    end
    render json: {
      shops: @shops
    }
  end

  # GET /rooms/:id/join
  def join
    redirect_to(root_path, alert: "この部屋は満員です。") && return if @room.limited?

    message = {}
    current_user.join(@room) ? message[:notice] = "ルームに参加しました！" : message[:alert] = "ルームマスターは部屋に参加できません。"
    redirect_to joining_user_path(current_user), message
  end

  # GET /rooms/search
  def search
    term = params[:keyword]
    @rooms = Room.search(term).page(params[:page]).per 6
    render :index
  end

  # GET /rooms/:id/exit
  def exit
    current_user.exit(@room) ? redirect_to(room_path(@room), notice: "ルームを退出しました。") : redirect_to(room_path(@room), alert: "あなたはこのルームのメンバーではありません。")
  end

  private

  def room_params
    params.require(:room).permit(:title, :content, :limit, :shop_name, :shop_url, :date)
  end

  def set_room
    @room = Room.find(params[:id])
  end

  def room_owner?
    redirect_to(root_path, alert: "このページにはアクセスできません。") and return unless @room.owner?(current_user)
  end

  def render_status_404(exception)
    render json: { errors: [exception] }, status: :not_found
  end

  def render_status_500(exception)
    render json: { errors: [exception] }, status: :internal_server_error
  end
end

app/helpers/rooms_helper.rb
require 'json'
require 'net/https'
require "uri"

module RoomsHelper
  def search_shops(term)
    query = {
      key: ENV["HOTPEPPER_API_KEY"],
      keyword: term,
      format: "json"
    }.to_query
    uri = URI("https://webservice.recruit.co.jp/hotpepper/shop/v1/?#{query}")
    http = Net::HTTP.new(uri.host, uri.port)
    http.use_ssl = true
    req = Net::HTTP::Get.new(uri)
    res = http.request(req)
    JSON.parse(res.body)
  end
end

app/views/rooms/_room.html.erb
<div class="room card">
  <div class="card-body">
    <div class="room-header d-flex">
      <%= link_to user_path(room.owner) do %>
        <%= image_tag profile_image_url(room.owner), class: "profile-image" %>
      <% end %>
      <h3 class="room-title mx-auto"><%= room.title %></h3>
    </div>
    <div class="room-content">
      <p><%= room.content[0, 20] %><%= "..." if room.content.length > 20 %></p>
      <p>お店：<a href="<%= room.shop_url %>"><%= room.shop_name %></a></p>
      <p>日付：<%= room.display_time %></p>
    </div>
    <div class="room-links d-flex">
      <div class="room-link-left">
        <%= link_to "見る", room_path(room), class: "card-link" %>
        <%= link_to "入室", join_room_path(room), class: "card-link" %>
        <%= link_to "編集", edit_room_path(room), class: "card-link" if room.owner? current_user%>
      </div>
      <div class="room-link-right">
        <div class="member-count">
          <svg xmlns="http://www.w3.org/2000/svg" width="25" height="25" fill="currentColor" class="bi bi-people" viewBox="0 0 16 16">
            <path d="M15 14s1 0 1-1-1-4-5-4-5 3-5 4 1 1 1 1h8zm-7.978-1A.261.261 0 0 1 7 12.996c.001-.264.167-1.03.76-1.72C8.312 10.629 9.282 10 11 10c1.717 0 2.687.63 3.24 1.276.593.69.758 1.457.76 1.72l-.008.002a.274.274 0 0 1-.014.002H7.022zM11 7a2 2 0 1 0 0-4 2 2 0 0 0 0 4zm3-2a3 3 0 1 1-6 0 3 3 0 0 1 6 0zM6.936 9.28a5.88 5.88 0 0 0-1.23-.247A7.35 7.35 0 0 0 5 9c-4 0-5 3-5 4 0 .667.333 1 1 1h4.216A2.238 2.238 0 0 1 5 13c0-1.01.377-2.042 1.09-2.904.243-.294.526-.569.846-.816zM4.92 10A5.493 5.493 0 0 0 4 13H1c0-.26.164-1.03.76-1.724.545-.636 1.492-1.256 3.16-1.275zM1.5 5.5a3 3 0 1 1 6 0 3 3 0 0 1-6 0zm3-2a2 2 0 1 0 0 4 2 2 0 0 0 0-4z"/>
          </svg>
          <%= room.members.count %>
        </div>
        <%= render 'bookmarks/bookmark_icon', room: room if user_signed_in? %>
        <% if room.owner? current_user %>
          <%= link_to room_path(room), method: :delete, class: "room-link-trash" do %>
            <svg xmlns="http://www.w3.org/2000/svg" width="25" height="25" fill="currentColor" class="bi bi-trash" viewBox="0 0 16 16">
              <path d="M5.5 5.5A.5.5 0 0 1 6 6v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5zm2.5 0a.5.5 0 0 1 .5.5v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5zm3 .5a.5.5 0 0 0-1 0v6a.5.5 0 0 0 1 0V6z"/>
              <path fill-rule="evenodd" d="M14.5 3a1 1 0 0 1-1 1H13v9a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V4h-.5a1 1 0 0 1-1-1V2a1 1 0 0 1 1-1H6a1 1 0 0 1 1-1h2a1 1 0 0 1 1 1h3.5a1 1 0 0 1 1 1v1zM4.118 4L4 4.059V13a1 1 0 0 0 1 1h6a1 1 0 0 0 1-1V4.059L11.882 4H4.118zM2.5 3V2h11v1h-11z"/>
            </svg>
          <% end %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/rooms/_room_form.html.erb
<%= form_with(model: @room, remote: true) do |f| %>
  <div class="form-group">
    <%= f.label :shop_name, class: "form-label" %>
    <%= f.text_field :shop_name, class: "form-control", id: "room_shop_name" %>
    <ul id="result"></ul>
  </div>

  <div class="form-group">
    <%= f.label :conditions, class: "form-label" %>
    <%= f.text_area :conditions, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :date, class: "form-label" %>
    <%= f.datetime_select :date, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :people_limit, class: "form-label" %>
    <%= f.select :people_limit, ["no-limit"] + (1..10).to_a, class: "form-control" %>
  </div>

  <div class="actions">
    <%= f.submit "Submit", class: "btn btn-primary" %></div>
<% end %>

app/views/rooms/edit.html.erb
<% provide(:title, "edit room") %>

<div class="content">
  <%= render 'rooms/shared/room_form', room: @room %>
</div>

app/views/rooms/index.html.erb
<% provide(:title, "All Rooms") %>

<div class="content">
  <%= form_tag(search_rooms_path, method: :get, class: "rooms-search") do %>
    <%= text_field_tag :keyword, nil, class: "form-control", placeholder: "ルーム検索" %>
    <%= submit_tag "検索", class: "btn btn-primary" %>
  <% end %>

  <div class="rooms text-center grid">
    <%= render @rooms %>
  </div>
  <div class="paginate-wrapper">
    <%= paginate @rooms %>
  </div>
</div>

app/views/rooms/new.html.erb
<% provide(:title, "new room") %>

<div class="content">
  <%= render 'rooms/shared/room_form', room: @room %>
</div>

app/views/rooms/show.html.erb
<% provide(:title, @room.title) %>

<div class="content">
  <div class="rooms-show-main-content d-flex mx-auto">
    <div class="user-card card">
      <%= image_tag profile_image_url(@room.owner), class: "profile-image" %>
      <h2><%= @room.owner.name %></h2>
      <ul class="list-group">
        <li class="list-group-item">
          <%= link_to "Rooms: ", rooms_path(@room.owner) %>
          <%= @room.owner.rooms.count %>
        </li>
        <li class="list-group-item">
          <%= link_to "Following: ", "#" %>
          <%= @room.owner.following.count %>
        </li>
        <li class="list-group-item">
          <%= link_to "Booked: ", bookmarks_path %>
          <%= @room.owner.bookmarks.count %>
        </li>
      </ul>
      <% if current_user && !current_user?(@room.owner) %>
        <div id="follow-button-<%= @room.owner.id %>">
          <%= render 'users/shared/follow_button', user: @room.owner %>
        </div>
      <% end %>
    </div>
    <div class="room-card card">
      <h1><%= @room.title %></h1>
      <p><%= @room.content %></p>
      <div class="room-card-footer d-flex justify-content-around">
        <ul class="room-info list-group">
          <li class="list-group-item"><strong>お店: </strong><a href="<%= @room.shop_url %>"><%= @room.shop_name %></a></li>
          <li class="list-group-item"><strong>人数: </strong><%= @room.members.count %> / <%= @room.limit %> 人</li>
          <li class="list-group-item"><strong>日付:</strong><%= @room.display_time %></li>
        </ul>
        <% unless @room.owner? current_user %>
          <% unless @room.member? current_user %>
            <div class="join-room-link" data-toggle="tooltip" data-placement="top" title="部屋に参加する">
              <%= link_to join_room_path do %>
                <svg xmlns="http://www.w3.org/2000/svg" fill="currentColor" class="join-room-icon bi bi-box-arrow-in-right" viewBox="0 0 16 16">
                  <path fill-rule="evenodd" d="M6 3.5a.5.5 0 0 1 .5-.5h8a.5.5 0 0 1 .5.5v9a.5.5 0 0 1-.5.5h-8a.5.5 0 0 1-.5-.5v-2a.5.5 0 0 0-1 0v2A1.5 1.5 0 0 0 6.5 14h8a1.5 1.5 0 0 0 1.5-1.5v-9A1.5 1.5 0 0 0 14.5 2h-8A1.5 1.5 0 0 0 5 3.5v2a.5.5 0 0 0 1 0v-2z"/>
                  <path fill-rule="evenodd" d="M11.854 8.354a.5.5 0 0 0 0-.708l-3-3a.5.5 0 1 0-.708.708L10.293 7.5H1.5a.5.5 0 0 0 0 1h8.793l-2.147 2.146a.5.5 0 0 0 .708.708l3-3z"/>
                </svg>
              <% end %>
            </div>
          <% else%>
            <div class="join-room-link" data-toggle="tooltip" data-placement="top" title="部屋から退出する">
              <%= link_to exit_room_path do %>
                <svg xmlns="http://www.w3.org/2000/svg" fill="currentColor" class="join-room-icon bi bi-box-arrow-left" viewBox="0 0 16 16">
                  <path fill-rule="evenodd" d="M6 12.5a.5.5 0 0 0 .5.5h8a.5.5 0 0 0 .5-.5v-9a.5.5 0 0 0-.5-.5h-8a.5.5 0 0 0-.5.5v2a.5.5 0 0 1-1 0v-2A1.5 1.5 0 0 1 6.5 2h8A1.5 1.5 0 0 1 16 3.5v9a1.5 1.5 0 0 1-1.5 1.5h-8A1.5 1.5 0 0 1 5 12.5v-2a.5.5 0 0 1 1 0v2z"/>
                  <path fill-rule="evenodd" d="M.146 8.354a.5.5 0 0 1 0-.708l3-3a.5.5 0 1 1 .708.708L1.707 7.5H10.5a.5.5 0 0 1 0 1H1.707l2.147 2.146a.5.5 0 0 1-.708.708l-3-3z"/>
                </svg>
              <% end %>
            </div>
          <% end %>
        <% else %>
          <div class="edit-room-link" data-toggle="tooltip" data-placement="top" title="部屋を編集する">
            <%= link_to edit_room_path do %>
              <svg xmlns="http://www.w3.org/2000/svg" fill="currentColor" class="edit-room-icon bi bi-pencil-fill" viewBox="0 0 16 16">
                <path d="M12.854.146a.5.5 0 0 0-.707 0L10.5 1.793 14.207 5.5l1.647-1.646a.5.5 0 0 0 0-.708l-3-3zm.646 6.061L9.793 2.5 3.293 9H3.5a.5.5 0 0 1 .5.5v.5h.5a.5.5 0 0 1 .5.5v.5h.5a.5.5 0 0 1 .5.5v.5h.5a.5.5 0 0 1 .5.5v.207l6.5-6.5zm-7.468 7.468A.5.5 0 0 1 6 13.5V13h-.5a.5.5 0 0 1-.5-.5V12h-.5a.5.5 0 0 1-.5-.5V11h-.5a.5.5 0 0 1-.5-.5V10h-.5a.499.499 0 0 1-.175-.032l-.179.178a.5.5 0 0 0-.11.168l-2 5a.5.5 0 0 0 .65.65l5-2a.5.5 0 0 0 .168-.11l.178-.178z"/>
              </svg>
            <% end %>
          </div>
          <div class="destroy-room-link">
            <%= link_to room_path(@room), method: :delete, data: { confirm: "削除しますか？" } do %>
              <svg xmlns="http://www.w3.org/2000/svg" fill="currentColor" class="destroy-room-icon bi bi-trash" viewBox="0 0 16 16">
                <path d="M5.5 5.5A.5.5 0 0 1 6 6v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5zm2.5 0a.5.5 0 0 1 .5.5v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5zm3 .5a.5.5 0 0 0-1 0v6a.5.5 0 0 0 1 0V6z"/>
                <path fill-rule="evenodd" d="M14.5 3a1 1 0 0 1-1 1H13v9a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V4h-.5a1 1 0 0 1-1-1V2a1 1 0 0 1 1-1H6a1 1 0 0 1 1-1h2a1 1 0 0 1 1 1h3.5a1 1 0 0 1 1 1v1zM4.118 4L4 4.059V13a1 1 0 0 0 1 1h6a1 1 0 0 0 1-1V4.059L11.882 4H4.118zM2.5 3V2h11v1h-11z"/>
              </svg>
            <% end %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
  <div class="user-page-content">
    <div class="collapse-links">
      <a class="collapse-link selected" data-toggle="collapse" href="#rooms" role="button" aria-expanded="false" aria-controls="rooms" onclick="$('#following').collapse('hide')">メンバー</a>
      <a class="collapse-link" data-toggle="collapse" href="#following" role="button" aria-expanded="false" aria-controls="following" onclick="$('#rooms').collapse('hide')">ブックマーク</a>
    </div>
    <div class="collapse show" id="rooms">
      <div class="rooms grid">
        <%= render @room.members %>
      </div>
    </div>
    <div class="collapse" id="following">
      <div class="rooms grid">
        <%= render @room.booked_by %></div>
    </div>
  </div>
</div>

<script>
  var collapseLink = $('.collapse-link');
  collapseLink.on('click', function() {
    collapseLink.removeClass('selected');
    $(this).addClass('selected');
  })
</script>